### ISSUE TITLE
Line by line comparison doesn't include last empty line

### ISSUE THREAD

**Issue by afshinm** [utkarshkukreti/diff.rs#10]
We are using this crate in rustfmt to make the diff. 

Someone has reported an issue (https://github.com/rust-lang-nursery/rustfmt/issues/1753), this is the digest of what is going on. Since you are using `str.lines()`, it doesn't include any empty line (i.e `boo\n` is just one line, which is not actually) so it causes some problems. What I'm trying to do is to change this crate so that it can detect and say that `left` has a trailing newline and `right` does not.

I can open a PR to patch but I just wanted to know if you have any suggestion for this? I was thinking about removing `str.lines()` and write a simple `str.split` and returns an empty iterator when the input is empty string.

**Comment by utkarshkukreti** [comment]
Hi @afshinm! Thanks for the bug report. Could you try out the solution in #11 and see if it fixes the rustfmt issue? I'll merge and make a new release once you confirm!
