### ISSUE TITLE
Why does `Result::Both` contain two values?

### ISSUE THREAD

**Issue by pokir** [utkarshkukreti/diff.rs#18]
Why does `Result::Both` contain two values if they will always be the same?

**Comment by utkarshkukreti** [comment]
They're not guaranteed to be the same, just that their `PartialEq` implementation returns `true`. The first element in `Result::Both` is guaranteed to be from the first input and the second from the second. A simple demonstration:

```rust
fn main() {
    let left = "foo\nbar\nbaz\nquux";
    let right = "foo\nbaz\nbar\nquux";

    for diff in diff::lines(left, right) {
        match diff {
            diff::Result::Left(l) => println!("-{:?}", l.as_ptr()),
            diff::Result::Both(l, r) => println!("={:?} {:?}", l.as_ptr(), r.as_ptr()),
            diff::Result::Right(r) => println!("+{:?}", r.as_ptr()),
        }
    }
}
```

Output:

```
=0x1043b5620 0x1043b5630
-0x1043b5624
=0x1043b5628 0x1043b5634
+0x1043b5638
=0x1043b562c 0x1043b563c
```

As you can see, in the equal lines, `l` and `r` point inside `left` and `right` respectively. If you compare them with `==` it'll return true but they're different objects in memory.
