### ISSUE TITLE
please include LICENSE text into archive

### ISSUE THREAD

**Issue by ignatenkobrain** [utkarshkukreti/diff.rs#9]
Since there are many variations of MIT license, Fedora requires license text to be present. Moreover, when you will relicense to ASL 2.0, that license itself requires text license to be present along with sources.

**Comment by utkarshkukreti** [comment]
@ignatenkobrain will do. Just curious - are you creating a Fedora package for a crate that depends on this crate? Is it `rustfmt`?

**Comment by ignatenkobrain** [comment]
@utkarshkukreti yes, exactly. (Though I already created it :))

**Comment by utkarshkukreti** [comment]
Done!
